%global tl_name fc
%global tl_revision 32796

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.4
Release:	%{tl_revision}.1
Summary:	Fonts for African languages
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/fonts/jknappen/fc
License:	gpl2
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/fc.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/fc.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
BuildRequires:	texlive-tlpkg
%texlive_base_requires
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The fonts are provided as Metafont source, in the familiar arrangement
of lots of (autogenerated) preamble files and a modest set of glyph
specifications. (A similar arrangement appears in the ec and lh font
bundles.)

